if has('win32') || has('win64')
    set   termencoding=cp932
endif
set   mouse=a
set   path+=/usr/include/**
set   ruler
set   hlsearch
set   smartcase
set nowrapscan
set nonumber
set noswapfile
set notitle
set   wildmenu
set   backspace=indent,eol,start
set   encoding=utf-8
set   fileencoding=utf-8
set   fileencodings=ucs-bom,utf-8,cp932
set   laststatus=2
set   statusline=%n\ %<%F%R%M%W%y%q%=\ %(%l,%c%V%)\ %p%%
set   grepprg=ack

if has('unnamedplus')
    set clipboard&
    set clipboard^=unnamedplus
endif

     map <C-n>     :cnext<CR>
     map <C-m>     :cprevious<CR>
nnoremap <leader>a :cclose<CR>

" Plugins
call plug#begin('~/.vim/plugged')
Plug 'ctrlpvim/ctrlp.vim', { 'tag': '*' }
Plug 'fatih/vim-go', { 'tag': '*' }
Plug 'davidhalter/jedi-vim', { 'tag': '*' }
call plug#end()

filetype indent plugin on
syntax on

" et=expandtab, ts=tabstop, sts=softtabstop, sw=shiftwidth
set shiftround
set et ts=4 sts=4 sw=4
augroup indent
    autocmd!
    autocmd FileType gitconfig setlocal noet ts=8 sts=8 sw=8
    autocmd FileType go        setlocal noet ts=4 sts=4 sw=4
    autocmd FileType make      setlocal noet ts=8 sts=8 sw=8
    autocmd FileType html      setlocal noet ts=2 sts=2 sw=2
augroup END

augroup golangSettings
    autocmd!
    autocmd FileType go nmap <leader>b  <Plug>(go-build)
    autocmd FileType go nmap <leader>r  <Plug>(go-run)
augroup END
