vim.cmd("runtime vimrc")

require("plugins/cmp")
require("plugins/inlay-hints")
require("plugins/gitsigns")
require("plugins/kanagawa")
require("plugins/lualine")
require("plugins/lsp")
require("plugins/lsp_signature")
require("plugins/null-ls")
require("plugins/nvim-tree")
require("plugins/nvim-treesitter")
require("plugins/telescope")
